[package]
name = "cortex-public-sale"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "cortex_public_sale"

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"

