[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cortex = "9qeww9s48ByyxzPuoiwhvYfB9dfG4Q3a1VnJrYcahwo6"
cortex_vault = "7nVZjbjEiJVPzaKBPDWJ5dPVMmcEBduDtiWi9o67nosS"
cortex_staking = "rYantWFyB4PsL36r9XB7nUb8TQ1pAhn9A87S6TbpMsr"
cortex_treasury = "GsMtBFGq3DWFGDqtJ6Fb4LjdB6sBADKL2Lix9xaYV7GS"
cortex_strategy = "WpEYz9eHtu3jhZkLsfgyyFpWR5C7bjswktpso5BWeQS"
cortex_token = "66oVB8Wiva4axdCw9EPG7TAurKVHFpvWXeHuHurPnEJ4"
cortex_private_sale = "H4s2UV6FcJhheHC3TP8LtjEx8kzXTLTZsKVM7jN52FmT"
cortex_vesting = "kGXFo5ugyV5mQF7jMtoKmtf89sLMXoQo3nxmrMRynH9"

[programs.devnet]
cortex = "9qeww9s48ByyxzPuoiwhvYfB9dfG4Q3a1VnJrYcahwo6"
cortex_vault = "7nVZjbjEiJVPzaKBPDWJ5dPVMmcEBduDtiWi9o67nosS"
cortex_staking = "rYantWFyB4PsL36r9XB7nUb8TQ1pAhn9A87S6TbpMsr"
cortex_treasury = "GsMtBFGq3DWFGDqtJ6Fb4LjdB6sBADKL2Lix9xaYV7GS"
cortex_strategy = "WpEYz9eHtu3jhZkLsfgyyFpWR5C7bjswktpso5BWeQS"
cortex_token = "66oVB8Wiva4axdCw9EPG7TAurKVHFpvWXeHuHurPnEJ4"
cortex_private_sale = "H4s2UV6FcJhheHC3TP8LtjEx8kzXTLTZsKVM7jN52FmT"
cortex_vesting = "kGXFo5ugyV5mQF7jMtoKmtf89sLMXoQo3nxmrMRynH9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/tmp/ico-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
